# generated by datamodel-codegen:
#   filename:  api-reference.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    EmailStr,
    Field,
    PositiveInt,
    RootModel,
    confloat,
    conint,
    constr,
)


class HealthGetResponse(BaseModel):
    status: str
    uptime: float
    timestamp: float


class Memory(BaseModel):
    rss: float
    heapTotal: float
    heapUsed: float
    external: float


class VersionGetResponse(BaseModel):
    version: str
    environment: str | None = None
    nodeVersion: str
    platform: str
    arch: str
    timestamp: str
    versions: dict[str, str]
    memory: Memory


class ApiKeysGetResponseItem(BaseModel):
    id: str
    name: str
    partialToken: str
    lastUsed: str | None = None
    createdAt: str
    permission: str


class ApiKeysGetResponse(RootModel[list[ApiKeysGetResponseItem]]):
    root: list[ApiKeysGetResponseItem]


class Permission(Enum):
    FULL = 'FULL'
    SENDING = 'SENDING'


class ApiKeysPostRequest(BaseModel):
    name: constr(min_length=1)
    permission: Permission | None = 'FULL'


class ApiKeysPostResponse(BaseModel):
    token: str


class ApiKeysIdDeleteResponse(BaseModel):
    pass


class SettingsGetResponse(BaseModel):
    id: str
    name: str
    plan: str
    dailyEmailLimit: float
    monthlyEmailLimit: float


class DayItem(BaseModel):
    type: str
    sent: float


class MonthItem(BaseModel):
    type: str
    sent: float


class AnalyticsGetResponse(BaseModel):
    day: list[DayItem]
    month: list[MonthItem]


class ActivityGetParametersQuery(BaseModel):
    page: PositiveInt | None = 1
    limit: conint(le=100, gt=0) | None = 50


class ActivityGetResponse(BaseModel):
    pass


class ActivityGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class AnalyticsTimeSeriesGetParametersQuery(BaseModel):
    days: str | None = None
    domain: str | None = None


class AnalyticsTimeSeriesGetResponse(BaseModel):
    pass


class AnalyticsReputationGetParametersQuery(BaseModel):
    domain: str | None = None


class AnalyticsReputationGetResponse(BaseModel):
    pass


class Status(Enum):
    SCHEDULED = 'SCHEDULED'
    QUEUED = 'QUEUED'
    SENT = 'SENT'
    DELIVERY_DELAYED = 'DELIVERY_DELAYED'
    BOUNCED = 'BOUNCED'
    REJECTED = 'REJECTED'
    RENDERING_FAILURE = 'RENDERING_FAILURE'
    DELIVERED = 'DELIVERED'
    OPENED = 'OPENED'
    CLICKED = 'CLICKED'
    COMPLAINED = 'COMPLAINED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    SUPPRESSED = 'SUPPRESSED'


class EventsGetParametersQuery(BaseModel):
    page: PositiveInt | None = 1
    limit: conint(le=100, gt=0) | None = 50
    status: Status | None = None
    startDate: AwareDatetime | None = None


class EventsGetResponse(BaseModel):
    pass


class EventsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class StatsGetParametersQuery(BaseModel):
    startDate: AwareDatetime | None = None
    endDate: AwareDatetime | None = None


class StatsGetResponse(BaseModel):
    pass


class StatsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class Period(Enum):
    day = 'day'
    week = 'week'
    month = 'month'


class MetricsGetParametersQuery(BaseModel):
    period: Period | None = 'month'


class MetricsGetResponse(BaseModel):
    pass


class MetricsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class Type(Enum):
    """
    DNS record type
    """

    MX = 'MX'
    TXT = 'TXT'


class DnsRecord(BaseModel):
    type: Type = Field(..., description='DNS record type', examples=['TXT'])
    name: str = Field(..., description='DNS record name', examples=['mail'])
    value: str = Field(
        ...,
        description='DNS record value',
        examples=['v=spf1 include:amazonses.com ~all'],
    )
    ttl: str = Field(..., description='DNS record TTL', examples=['Auto'])
    priority: str | None = Field(
        None, description='DNS record priority', examples=['10']
    )
    status: str = Field(..., description='The status of the domain')
    recommended: bool | None = Field(
        None, description='Whether the record is recommended'
    )


class DomainsGetResponseItem(BaseModel):
    id: str = Field(
        ...,
        description='The ID of the domain',
        examples=['0Lleb1FOUnB60jSueJ/mkPId1vrdB68T8/u9tiInsi4='],
    )
    name: str = Field(
        ..., description='The name of the domain', examples=['example.com']
    )
    teamId: str = Field(
        ...,
        description='The ID of the team',
        examples=['jonVNF8M+EbJObaRAz2XBHnoJ6Add/tazP9lfOiPJ3E='],
    )
    status: str = Field(..., description='The status of the domain')
    region: str | None = Field(
        'us-east-1', description='The region of the domain', examples=['us-east-1']
    )
    clickTracking: bool | None = Field(
        False, description='Whether click tracking is enabled', examples=[False]
    )
    openTracking: bool | None = Field(
        False, description='Whether open tracking is enabled', examples=[False]
    )
    publicKey: str = Field(..., description='The public key of the domain')
    dkimStatus: str | None = Field(None, description='The DKIM status of the domain')
    spfDetails: str | None = Field(None, description='The SPF details of the domain')
    createdAt: str = Field(..., description='The creation date of the domain')
    updatedAt: str = Field(..., description='The last update date of the domain')
    dmarcAdded: bool | None = Field(False, description='Whether DMARC is added')
    isVerifying: bool | None = Field(
        False, description='Whether the domain is verifying'
    )
    errorMessage: str | None = Field(
        None, description='The error message of the domain'
    )
    subdomain: str | None = Field(None, description='The subdomain of the domain')
    verificationError: str | None = Field(
        None, description='The verification error of the domain'
    )
    lastCheckedTime: str | None = Field(
        None, description='The last checked time of the domain'
    )
    dnsRecords: list[DnsRecord] = Field(
        ..., description='The DNS records of the domain'
    )


class DomainsGetResponse(RootModel[list[DomainsGetResponseItem]]):
    root: list[DomainsGetResponseItem]


class DomainsPostRequest(BaseModel):
    name: str
    region: str


class DnsRecord1(BaseModel):
    type: Type = Field(..., description='DNS record type', examples=['TXT'])
    name: str = Field(..., description='DNS record name', examples=['mail'])
    value: str = Field(
        ...,
        description='DNS record value',
        examples=['v=spf1 include:amazonses.com ~all'],
    )
    ttl: str = Field(..., description='DNS record TTL', examples=['Auto'])
    priority: str | None = Field(
        None, description='DNS record priority', examples=['10']
    )
    status: str = Field(..., description='The status of the domain')
    recommended: bool | None = Field(
        None, description='Whether the record is recommended'
    )


class DomainsPostResponse(BaseModel):
    id: str = Field(
        ...,
        description='The ID of the domain',
        examples=['0Lleb1FOUnB60jSueJ/mkPId1vrdB68T8/u9tiInsi4='],
    )
    name: str = Field(
        ..., description='The name of the domain', examples=['example.com']
    )
    teamId: str = Field(
        ...,
        description='The ID of the team',
        examples=['jonVNF8M+EbJObaRAz2XBHnoJ6Add/tazP9lfOiPJ3E='],
    )
    status: str = Field(..., description='The status of the domain')
    region: str | None = Field(
        'us-east-1', description='The region of the domain', examples=['us-east-1']
    )
    clickTracking: bool | None = Field(
        False, description='Whether click tracking is enabled', examples=[False]
    )
    openTracking: bool | None = Field(
        False, description='Whether open tracking is enabled', examples=[False]
    )
    publicKey: str = Field(..., description='The public key of the domain')
    dkimStatus: str | None = Field(None, description='The DKIM status of the domain')
    spfDetails: str | None = Field(None, description='The SPF details of the domain')
    createdAt: str = Field(..., description='The creation date of the domain')
    updatedAt: str = Field(..., description='The last update date of the domain')
    dmarcAdded: bool | None = Field(False, description='Whether DMARC is added')
    isVerifying: bool | None = Field(
        False, description='Whether the domain is verifying'
    )
    errorMessage: str | None = Field(
        None, description='The error message of the domain'
    )
    subdomain: str | None = Field(None, description='The subdomain of the domain')
    verificationError: str | None = Field(
        None, description='The verification error of the domain'
    )
    lastCheckedTime: str | None = Field(
        None, description='The last checked time of the domain'
    )
    dnsRecords: list[DnsRecord1] = Field(
        ..., description='The DNS records of the domain'
    )


class DomainsIdAnalyticsGetParametersQuery(BaseModel):
    period: Period | None = 'month'


class DomainsIdAnalyticsGetResponseItem(BaseModel):
    date: str = Field(..., description='The date of the analytics')
    sent: float = Field(..., description='Number of emails sent')
    delivered: float = Field(..., description='Number of emails delivered')
    opened: float = Field(..., description='Number of emails opened')
    clicked: float = Field(..., description='Number of emails clicked')
    bounced: float = Field(..., description='Number of emails bounced')
    complained: float = Field(..., description='Number of emails complained')


class DomainsIdAnalyticsGetResponse(
    RootModel[list[DomainsIdAnalyticsGetResponseItem]]
):
    root: list[DomainsIdAnalyticsGetResponseItem]


class DomainsIdAnalyticsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class DomainsIdStatsGetParametersQuery(BaseModel):
    startDate: str | None = None
    endDate: str | None = None


class DomainsIdStatsGetResponse(BaseModel):
    totalSent: float = Field(..., description='Total emails sent')
    totalDelivered: float = Field(..., description='Total emails delivered')
    totalOpened: float = Field(..., description='Total emails opened')
    totalClicked: float = Field(..., description='Total emails clicked')
    totalBounced: float = Field(..., description='Total emails bounced')
    totalComplained: float = Field(..., description='Total emails complained')
    deliveryRate: float = Field(..., description='Delivery rate percentage')
    openRate: float = Field(..., description='Open rate percentage')
    clickRate: float = Field(..., description='Click rate percentage')
    bounceRate: float = Field(..., description='Bounce rate percentage')
    complaintRate: float = Field(..., description='Complaint rate percentage')


class DomainsIdStatsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class DomainsIdVerifyPutResponse(BaseModel):
    pass


class DnsRecord2(BaseModel):
    type: Type = Field(..., description='DNS record type', examples=['TXT'])
    name: str = Field(..., description='DNS record name', examples=['mail'])
    value: str = Field(
        ...,
        description='DNS record value',
        examples=['v=spf1 include:amazonses.com ~all'],
    )
    ttl: str = Field(..., description='DNS record TTL', examples=['Auto'])
    priority: str | None = Field(
        None, description='DNS record priority', examples=['10']
    )
    status: str = Field(..., description='The status of the domain')
    recommended: bool | None = Field(
        None, description='Whether the record is recommended'
    )


class DomainsIdGetResponse(BaseModel):
    id: str = Field(
        ...,
        description='The ID of the domain',
        examples=['0Lleb1FOUnB60jSueJ/mkPId1vrdB68T8/u9tiInsi4='],
    )
    name: str = Field(
        ..., description='The name of the domain', examples=['example.com']
    )
    teamId: str = Field(
        ...,
        description='The ID of the team',
        examples=['jonVNF8M+EbJObaRAz2XBHnoJ6Add/tazP9lfOiPJ3E='],
    )
    status: str = Field(..., description='The status of the domain')
    region: str | None = Field(
        'us-east-1', description='The region of the domain', examples=['us-east-1']
    )
    clickTracking: bool | None = Field(
        False, description='Whether click tracking is enabled', examples=[False]
    )
    openTracking: bool | None = Field(
        False, description='Whether open tracking is enabled', examples=[False]
    )
    publicKey: str = Field(..., description='The public key of the domain')
    dkimStatus: str | None = Field(None, description='The DKIM status of the domain')
    spfDetails: str | None = Field(None, description='The SPF details of the domain')
    createdAt: str = Field(..., description='The creation date of the domain')
    updatedAt: str = Field(..., description='The last update date of the domain')
    dmarcAdded: bool | None = Field(False, description='Whether DMARC is added')
    isVerifying: bool | None = Field(
        False, description='Whether the domain is verifying'
    )
    errorMessage: str | None = Field(
        None, description='The error message of the domain'
    )
    subdomain: str | None = Field(None, description='The subdomain of the domain')
    verificationError: str | None = Field(
        None, description='The verification error of the domain'
    )
    lastCheckedTime: str | None = Field(
        None, description='The last checked time of the domain'
    )
    dnsRecords: list[DnsRecord2] = Field(
        ..., description='The DNS records of the domain'
    )


class DomainsIdDeleteResponse(BaseModel):
    pass


class EmailsBouncesGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20


class EmailsBouncesGetResponse(BaseModel):
    pass


class EmailsComplaintsGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20


class EmailsComplaintsGetResponse(BaseModel):
    pass


class EmailsUnsubscribesGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20


class EmailsUnsubscribesGetResponse(BaseModel):
    pass


class EmailsPostRequest(BaseModel):
    to: str | list[str]
    from_: str = Field(..., alias='from')
    subject: constr(min_length=1) | None = Field(
        None, description='Optional when templateId is provided'
    )
    templateId: str | None = Field(
        None, description='ID of a template from the dashboard'
    )
    variables: dict[str, str] | None = None
    replyTo: str | list[str] | None = None
    cc: str | list[str] | None = None
    bcc: str | list[str] | None = None
    text: constr(min_length=1) | None = None
    html: constr(min_length=1) | None = None
    headers: dict[str, constr(min_length=1)] | None = Field(
        None, description='Custom headers to included with the emails'
    )
    attachments: list[dict[str, Any]] | None = Field(None, max_length=10)
    scheduledAt: AwareDatetime | None = None
    inReplyToId: str | None = None


class EmailsPostResponse(BaseModel):
    pass


class EmailsGetParametersQuery(BaseModel):
    page: str | None = Field('1', examples=['1'])
    limit: str | None = Field('50', examples=['50'])
    startDate: AwareDatetime | None = Field(None, examples=['2024-01-01T00:00:00Z'])
    endDate: AwareDatetime | None = Field(None, examples=['2024-01-31T23:59:59Z'])
    domainId: str | list[str] | None = Field(
        None, examples=['lftl0JMqTsuLpW2sG98qI/T2mUG4R+On+5OIBOY3Qa4=']
    )


class EmailsGetResponse(BaseModel):
    pass


class EmailsBatchPostRequestItem(BaseModel):
    to: str | list[str]
    from_: str = Field(..., alias='from')
    subject: constr(min_length=1) | None = Field(
        None, description='Optional when templateId is provided'
    )
    templateId: str | None = Field(
        None, description='ID of a template from the dashboard'
    )
    variables: dict[str, str] | None = None
    replyTo: str | list[str] | None = None
    cc: str | list[str] | None = None
    bcc: str | list[str] | None = None
    text: constr(min_length=1) | None = None
    html: constr(min_length=1) | None = None
    headers: dict[str, constr(min_length=1)] | None = Field(
        None, description='Custom headers to included with the emails'
    )
    attachments: list[dict[str, Any]] | None = Field(None, max_length=10)
    scheduledAt: AwareDatetime | None = None
    inReplyToId: str | None = None


class EmailsBatchPostRequest(RootModel[list[EmailsBatchPostRequestItem]]):
    root: list[EmailsBatchPostRequestItem] = Field(..., max_length=100, min_length=1)


class EmailsBatchPostResponse(BaseModel):
    pass


class EmailsEmailIdEventsGetParametersQuery(BaseModel):
    page: PositiveInt | None = 1
    limit: conint(le=100, gt=0) | None = 50
    status: Status | None = None
    startDate: AwareDatetime | None = None


class EmailsEmailIdEventsGetResponse(BaseModel):
    pass


class EmailsEmailIdEventsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class EmailsEmailIdGetResponse(BaseModel):
    pass


class EmailsEmailIdPatchRequest(BaseModel):
    pass


class EmailsEmailIdPatchResponse(BaseModel):
    pass


class EmailsEmailIdCancelPostResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsPostRequest(BaseModel):
    email: EmailStr
    firstName: str | None = None
    lastName: str | None = None
    properties: dict[str, str] | None = None
    subscribed: bool | None = None


class ContactBooksContactBookIdContactsPostResponse(BaseModel):
    contactId: str | None = None


class ContactBooksContactBookIdContactsGetParametersQuery(BaseModel):
    emails: str | None = None
    page: float | None = None
    limit: float | None = None
    ids: str | None = None


class ContactBooksContactBookIdContactsGetResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdPatchRequest(BaseModel):
    firstName: str | None = None
    lastName: str | None = None
    properties: dict[str, str] | None = None
    subscribed: bool | None = None


class ContactBooksContactBookIdContactsContactIdPatchResponse(BaseModel):
    contactId: str | None = None


class ContactBooksContactBookIdContactsContactIdGetResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdPutRequest(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdPutResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdDeleteResponse(BaseModel):
    pass


class CampaignsPostRequest(BaseModel):
    name: constr(min_length=1)
    from_: constr(min_length=1) = Field(..., alias='from')
    subject: constr(min_length=1)
    previewText: str | None = None
    contactBookId: constr(min_length=1)
    content: constr(min_length=1) | None = None
    html: constr(min_length=1) | None = None
    replyTo: constr(min_length=1) | list[constr(min_length=1)] | None = None
    cc: constr(min_length=1) | list[constr(min_length=1)] | None = None
    bcc: constr(min_length=1) | list[constr(min_length=1)] | None = None
    sendNow: bool | None = None
    scheduledAt: str | None = Field(
        None,
        description="Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')",
    )
    batchSize: conint(ge=1, le=100000) | None = None


class CampaignsPostResponse(BaseModel):
    id: str
    name: str
    from_: str = Field(..., alias='from')
    subject: str
    previewText: str
    contactBookId: str
    html: str
    content: str
    status: str
    scheduledAt: AwareDatetime
    batchSize: int
    batchWindowMinutes: int
    total: int
    sent: int
    delivered: int
    opened: int
    clicked: int
    unsubscribed: int
    bounced: int
    hardBounced: int
    complained: int
    replyTo: list[str]
    cc: list[str]
    bcc: list[str]
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class CampaignsGetResponseItem(BaseModel):
    id: str
    name: str
    subject: str
    status: str | None = None
    created_at: str
    sent: float | None = 0
    delivered: float | None = 0
    opened: float | None = 0
    clicked: float | None = 0


class CampaignsGetResponse(RootModel[list[CampaignsGetResponseItem]]):
    root: list[CampaignsGetResponseItem]


class CampaignsCampaignIdGetResponse(BaseModel):
    id: str
    name: str
    from_: str = Field(..., alias='from')
    subject: str
    previewText: str
    contactBookId: str
    html: str
    content: str
    status: str
    scheduledAt: AwareDatetime
    batchSize: int
    batchWindowMinutes: int
    total: int
    sent: int
    delivered: int
    opened: int
    clicked: int
    unsubscribed: int
    bounced: int
    hardBounced: int
    complained: int
    replyTo: list[str]
    cc: list[str]
    bcc: list[str]
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class CampaignsCampaignIdSchedulePostRequest(BaseModel):
    scheduledAt: str | None = Field(
        None,
        description="Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')",
    )
    batchSize: conint(ge=1, le=100000) | None = None


class CampaignsCampaignIdSchedulePostResponse(BaseModel):
    pass


class CampaignsCampaignIdPausePostResponse(BaseModel):
    pass


class CampaignsCampaignIdResumePostResponse(BaseModel):
    pass


class ContactBooksPostRequest(BaseModel):
    name: constr(min_length=1)
    emoji: str | None = None
    properties: dict[str, str] | None = None


class ContactBooksPostResponse(BaseModel):
    id: str
    name: str
    emoji: str
    properties: Any | None = None
    teamId: str
    createdAt: str
    updatedAt: str


class ContactBooksGetResponse(RootModel[list[dict[str, Any]]]):
    root: list[dict[str, Any]]


class Details(BaseModel):
    totalContacts: float
    unsubscribedContacts: float
    campaigns: list[Any]


class ContactBooksIdGetResponse(BaseModel):
    id: str
    name: str
    emoji: str
    properties: Any | None = None
    teamId: str
    createdAt: str
    updatedAt: str
    details: Details


class ContactBooksIdPatchRequest(BaseModel):
    name: str | None = None
    emoji: str | None = None
    properties: dict[str, str] | None = None


class ContactBooksIdPatchResponse(BaseModel):
    id: str
    name: str


class ContactBooksIdDeleteResponse(BaseModel):
    success: bool


class TemplatesPostRequest(BaseModel):
    name: constr(min_length=1)
    subject: constr(min_length=1)
    html: str | None = None
    content: str | None = None


class TemplatesPostResponse(BaseModel):
    id: str


class Datum(BaseModel):
    id: str
    name: str
    subject: str
    html: str
    content: str
    teamId: str
    createdAt: str
    updatedAt: str


class TemplatesGetResponse(BaseModel):
    data: list[Datum]


class TemplatesIdGetResponse(BaseModel):
    id: str
    name: str
    subject: str
    html: str
    content: str
    teamId: str
    createdAt: str
    updatedAt: str


class TemplatesIdPatchRequest(BaseModel):
    name: constr(min_length=1) | None = None
    subject: constr(min_length=1) | None = None
    html: str | None = None
    content: str | None = None


class TemplatesIdPatchResponse(BaseModel):
    success: bool


class TemplatesIdDeleteResponse(BaseModel):
    success: bool


class Reason(Enum):
    HARD_BOUNCE = 'HARD_BOUNCE'
    COMPLAINT = 'COMPLAINT'
    MANUAL = 'MANUAL'
    UNSUBSCRIBE = 'UNSUBSCRIBE'


class SuppressionsGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20
    search: str | None = None
    reason: Reason | None = None


class SuppressionsGetResponse(BaseModel):
    pass


class SuppressionsPostRequest(BaseModel):
    email: EmailStr
    reason: Reason
    source: str | None = None


class SuppressionsPostResponse(BaseModel):
    id: str
    email: str
    reason: str
    source: str | None = None
    createdAt: str


class SuppressionsEmailEmailDeleteResponse(BaseModel):
    pass


class EventType(Enum):
    contact_created = 'contact.created'
    contact_updated = 'contact.updated'
    contact_deleted = 'contact.deleted'
    domain_created = 'domain.created'
    domain_verified = 'domain.verified'
    domain_updated = 'domain.updated'
    domain_deleted = 'domain.deleted'
    email_queued = 'email.queued'
    email_sent = 'email.sent'
    email_delivery_delayed = 'email.delivery_delayed'
    email_delivered = 'email.delivered'
    email_bounced = 'email.bounced'
    email_rejected = 'email.rejected'
    email_rendering_failure = 'email.rendering_failure'
    email_complained = 'email.complained'
    email_failed = 'email.failed'
    email_cancelled = 'email.cancelled'
    email_suppressed = 'email.suppressed'
    email_opened = 'email.opened'
    email_clicked = 'email.clicked'


class WebhooksPostRequest(BaseModel):
    url: AnyUrl
    description: str | None = None
    eventTypes: list[EventType]
    secret: constr(min_length=16) | None = None


class WebhooksPostResponse(BaseModel):
    """
    Webhook details
    """

    id: str
    url: str
    description: str
    eventTypes: list[EventType]
    status: str
    secret: str
    apiVersion: str
    consecutiveFailures: float
    lastSuccessAt: str
    lastFailureAt: str
    createdAt: str
    updatedAt: str
    teamId: str
    createdByUserId: str


class WebhooksPostResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class WebhooksGetResponseItem(BaseModel):
    """
    Webhook details
    """

    id: str
    url: str
    description: str
    eventTypes: list[EventType]
    status: str
    secret: str
    apiVersion: str
    consecutiveFailures: float
    lastSuccessAt: str
    lastFailureAt: str
    createdAt: str
    updatedAt: str
    teamId: str
    createdByUserId: str


class WebhooksGetResponse(RootModel[list[WebhooksGetResponseItem]]):
    root: list[WebhooksGetResponseItem]


class WebhooksGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class WebhooksIdGetResponse(BaseModel):
    """
    Webhook details
    """

    id: str
    url: str
    description: str
    eventTypes: list[EventType]
    status: str
    secret: str
    apiVersion: str
    consecutiveFailures: float
    lastSuccessAt: str
    lastFailureAt: str
    createdAt: str
    updatedAt: str
    teamId: str
    createdByUserId: str


class WebhooksIdGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class WebhooksIdPatchRequest(BaseModel):
    url: AnyUrl | None = None
    description: str | None = None
    eventTypes: list[EventType] | None = None
    active: bool | None = None
    rotateSecret: bool | None = None
    secret: constr(min_length=16) | None = None


class WebhooksIdPatchResponse(BaseModel):
    """
    Webhook details
    """

    id: str
    url: str
    description: str
    eventTypes: list[EventType]
    status: str
    secret: str
    apiVersion: str
    consecutiveFailures: float
    lastSuccessAt: str
    lastFailureAt: str
    createdAt: str
    updatedAt: str
    teamId: str
    createdByUserId: str


class WebhooksIdPatchResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class WebhooksIdDeleteResponse(BaseModel):
    """
    Webhook details
    """

    id: str
    url: str
    description: str
    eventTypes: list[EventType]
    status: str
    secret: str
    apiVersion: str
    consecutiveFailures: float
    lastSuccessAt: str
    lastFailureAt: str
    createdAt: str
    updatedAt: str
    teamId: str
    createdByUserId: str


class WebhooksIdDeleteResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class WebhooksIdTestPostResponse(BaseModel):
    """
    Webhook call details
    """

    id: str
    type: str
    createdAt: str
    updatedAt: str
    teamId: str
    status: str
    webhookId: str
    payload: str
    attempt: float
    nextAttemptAt: str
    lastError: str
    responseStatus: float
    responseTimeMs: float
    responseText: str


class WebhooksIdTestPostResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class TeamGetResponse(BaseModel):
    pass


class TeamGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None


class TeamsGetResponse(BaseModel):
    pass


class TeamsGetResponse1(BaseModel):
    """
    Error response
    """

    code: str
    message: str
    docs: str | None = None
