# generated by datamodel-codegen:
#   filename:  api-reference.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    EmailStr,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class HealthGetResponse(BaseModel):
    status: str
    uptime: float
    timestamp: float


class ApiKeysGetResponseItem(BaseModel):
    id: str
    name: str
    partialToken: str
    lastUsed: str | None = None
    createdAt: str
    permission: str


class ApiKeysGetResponse(RootModel[list[ApiKeysGetResponseItem]]):
    root: list[ApiKeysGetResponseItem]


class Permission(Enum):
    FULL = 'FULL'
    SENDING = 'SENDING'


class ApiKeysPostRequest(BaseModel):
    name: constr(min_length=1)
    permission: Permission | None = 'FULL'


class ApiKeysPostResponse(BaseModel):
    pass


class ApiKeysIdDeleteResponse(BaseModel):
    pass


class SettingsGetResponse(BaseModel):
    pass


class AnalyticsGetResponse(BaseModel):
    pass


class AnalyticsTimeSeriesGetParametersQuery(BaseModel):
    days: str | None = None
    domain: str | None = None


class AnalyticsTimeSeriesGetResponse(BaseModel):
    pass


class AnalyticsReputationGetParametersQuery(BaseModel):
    domain: str | None = None


class AnalyticsReputationGetResponse(BaseModel):
    pass


class Type(Enum):
    """
    DNS record type
    """

    MX = 'MX'
    TXT = 'TXT'


class DnsRecord(BaseModel):
    type: Type = Field(..., description='DNS record type', examples=['TXT'])
    name: str = Field(..., description='DNS record name', examples=['mail'])
    value: str = Field(
        ...,
        description='DNS record value',
        examples=['v=spf1 include:amazonses.com ~all'],
    )
    ttl: str = Field(..., description='DNS record TTL', examples=['Auto'])
    priority: str | None = Field(
        None, description='DNS record priority', examples=['10']
    )
    status: str = Field(..., description='The status of the domain')
    recommended: bool | None = Field(
        None, description='Whether the record is recommended'
    )


class DomainsGetResponseItem(BaseModel):
    id: str = Field(
        ...,
        description='The ID of the domain',
        examples=['0Lleb1FOUnB60jSueJ/mkPId1vrdB68T8/u9tiInsi4='],
    )
    name: str = Field(
        ..., description='The name of the domain', examples=['example.com']
    )
    teamId: str = Field(
        ...,
        description='The ID of the team',
        examples=['jonVNF8M+EbJObaRAz2XBHnoJ6Add/tazP9lfOiPJ3E='],
    )
    status: str = Field(..., description='The status of the domain')
    region: str | None = Field(
        'us-east-1', description='The region of the domain', examples=['us-east-1']
    )
    clickTracking: bool | None = Field(
        False, description='Whether click tracking is enabled', examples=[False]
    )
    openTracking: bool | None = Field(
        False, description='Whether open tracking is enabled', examples=[False]
    )
    publicKey: str = Field(..., description='The public key of the domain')
    dkimStatus: str | None = Field(None, description='The DKIM status of the domain')
    spfDetails: str | None = Field(None, description='The SPF details of the domain')
    createdAt: str = Field(..., description='The creation date of the domain')
    updatedAt: str = Field(..., description='The last update date of the domain')
    dmarcAdded: bool | None = Field(False, description='Whether DMARC is added')
    isVerifying: bool | None = Field(
        False, description='Whether the domain is verifying'
    )
    errorMessage: str | None = Field(
        None, description='The error message of the domain'
    )
    subdomain: str | None = Field(None, description='The subdomain of the domain')
    verificationError: str | None = Field(
        None, description='The verification error of the domain'
    )
    lastCheckedTime: str | None = Field(
        None, description='The last checked time of the domain'
    )
    dnsRecords: list[DnsRecord] = Field(
        ..., description='The DNS records of the domain'
    )


class DomainsGetResponse(RootModel[list[DomainsGetResponseItem]]):
    root: list[DomainsGetResponseItem]


class DomainsPostRequest(BaseModel):
    name: str
    region: str


class DnsRecord1(BaseModel):
    type: Type = Field(..., description='DNS record type', examples=['TXT'])
    name: str = Field(..., description='DNS record name', examples=['mail'])
    value: str = Field(
        ...,
        description='DNS record value',
        examples=['v=spf1 include:amazonses.com ~all'],
    )
    ttl: str = Field(..., description='DNS record TTL', examples=['Auto'])
    priority: str | None = Field(
        None, description='DNS record priority', examples=['10']
    )
    status: str = Field(..., description='The status of the domain')
    recommended: bool | None = Field(
        None, description='Whether the record is recommended'
    )


class DomainsPostResponse(BaseModel):
    id: str = Field(
        ...,
        description='The ID of the domain',
        examples=['0Lleb1FOUnB60jSueJ/mkPId1vrdB68T8/u9tiInsi4='],
    )
    name: str = Field(
        ..., description='The name of the domain', examples=['example.com']
    )
    teamId: str = Field(
        ...,
        description='The ID of the team',
        examples=['jonVNF8M+EbJObaRAz2XBHnoJ6Add/tazP9lfOiPJ3E='],
    )
    status: str = Field(..., description='The status of the domain')
    region: str | None = Field(
        'us-east-1', description='The region of the domain', examples=['us-east-1']
    )
    clickTracking: bool | None = Field(
        False, description='Whether click tracking is enabled', examples=[False]
    )
    openTracking: bool | None = Field(
        False, description='Whether open tracking is enabled', examples=[False]
    )
    publicKey: str = Field(..., description='The public key of the domain')
    dkimStatus: str | None = Field(None, description='The DKIM status of the domain')
    spfDetails: str | None = Field(None, description='The SPF details of the domain')
    createdAt: str = Field(..., description='The creation date of the domain')
    updatedAt: str = Field(..., description='The last update date of the domain')
    dmarcAdded: bool | None = Field(False, description='Whether DMARC is added')
    isVerifying: bool | None = Field(
        False, description='Whether the domain is verifying'
    )
    errorMessage: str | None = Field(
        None, description='The error message of the domain'
    )
    subdomain: str | None = Field(None, description='The subdomain of the domain')
    verificationError: str | None = Field(
        None, description='The verification error of the domain'
    )
    lastCheckedTime: str | None = Field(
        None, description='The last checked time of the domain'
    )
    dnsRecords: list[DnsRecord1] = Field(
        ..., description='The DNS records of the domain'
    )


class DomainsIdVerifyPutResponse(BaseModel):
    pass


class DnsRecord2(BaseModel):
    type: Type = Field(..., description='DNS record type', examples=['TXT'])
    name: str = Field(..., description='DNS record name', examples=['mail'])
    value: str = Field(
        ...,
        description='DNS record value',
        examples=['v=spf1 include:amazonses.com ~all'],
    )
    ttl: str = Field(..., description='DNS record TTL', examples=['Auto'])
    priority: str | None = Field(
        None, description='DNS record priority', examples=['10']
    )
    status: str = Field(..., description='The status of the domain')
    recommended: bool | None = Field(
        None, description='Whether the record is recommended'
    )


class DomainsIdGetResponse(BaseModel):
    id: str = Field(
        ...,
        description='The ID of the domain',
        examples=['0Lleb1FOUnB60jSueJ/mkPId1vrdB68T8/u9tiInsi4='],
    )
    name: str = Field(
        ..., description='The name of the domain', examples=['example.com']
    )
    teamId: str = Field(
        ...,
        description='The ID of the team',
        examples=['jonVNF8M+EbJObaRAz2XBHnoJ6Add/tazP9lfOiPJ3E='],
    )
    status: str = Field(..., description='The status of the domain')
    region: str | None = Field(
        'us-east-1', description='The region of the domain', examples=['us-east-1']
    )
    clickTracking: bool | None = Field(
        False, description='Whether click tracking is enabled', examples=[False]
    )
    openTracking: bool | None = Field(
        False, description='Whether open tracking is enabled', examples=[False]
    )
    publicKey: str = Field(..., description='The public key of the domain')
    dkimStatus: str | None = Field(None, description='The DKIM status of the domain')
    spfDetails: str | None = Field(None, description='The SPF details of the domain')
    createdAt: str = Field(..., description='The creation date of the domain')
    updatedAt: str = Field(..., description='The last update date of the domain')
    dmarcAdded: bool | None = Field(False, description='Whether DMARC is added')
    isVerifying: bool | None = Field(
        False, description='Whether the domain is verifying'
    )
    errorMessage: str | None = Field(
        None, description='The error message of the domain'
    )
    subdomain: str | None = Field(None, description='The subdomain of the domain')
    verificationError: str | None = Field(
        None, description='The verification error of the domain'
    )
    lastCheckedTime: str | None = Field(
        None, description='The last checked time of the domain'
    )
    dnsRecords: list[DnsRecord2] = Field(
        ..., description='The DNS records of the domain'
    )


class DomainsIdDeleteResponse(BaseModel):
    pass


class EmailsEmailIdGetResponse(BaseModel):
    pass


class EmailsEmailIdPatchRequest(BaseModel):
    pass


class EmailsEmailIdPatchResponse(BaseModel):
    pass


class EmailsGetParametersQuery(BaseModel):
    page: str | None = Field('1', examples=['1'])
    limit: str | None = Field('50', examples=['50'])
    startDate: AwareDatetime | None = Field(None, examples=['2024-01-01T00:00:00Z'])
    endDate: AwareDatetime | None = Field(None, examples=['2024-01-31T23:59:59Z'])
    domainId: str | list[str] | None = Field(
        None, examples=['lftl0JMqTsuLpW2sG98qI/T2mUG4R+On+5OIBOY3Qa4=']
    )


class EmailsGetResponse(BaseModel):
    pass


class EmailsPostRequest(BaseModel):
    to: str | list[str]
    from_: str = Field(..., alias='from')
    subject: constr(min_length=1) | None = Field(
        None, description='Optional when templateId is provided'
    )
    templateId: str | None = Field(
        None, description='ID of a template from the dashboard'
    )
    variables: dict[str, str] | None = None
    replyTo: str | list[str] | None = None
    cc: str | list[str] | None = None
    bcc: str | list[str] | None = None
    text: constr(min_length=1) | None = None
    html: constr(min_length=1) | None = None
    headers: dict[str, constr(min_length=1)] | None = Field(
        None, description='Custom headers to included with the emails'
    )
    attachments: list[dict[str, Any]] | None = Field(None, max_length=10)
    scheduledAt: AwareDatetime | None = None
    inReplyToId: str | None = None


class EmailsPostResponse(BaseModel):
    pass


class EmailsBouncesGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20


class EmailsBouncesGetResponse(BaseModel):
    pass


class EmailsComplaintsGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20


class EmailsComplaintsGetResponse(BaseModel):
    pass


class EmailsUnsubscribesGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20


class EmailsUnsubscribesGetResponse(BaseModel):
    pass


class EmailsBatchPostRequestItem(BaseModel):
    to: str | list[str]
    from_: str = Field(..., alias='from')
    subject: constr(min_length=1) | None = Field(
        None, description='Optional when templateId is provided'
    )
    templateId: str | None = Field(
        None, description='ID of a template from the dashboard'
    )
    variables: dict[str, str] | None = None
    replyTo: str | list[str] | None = None
    cc: str | list[str] | None = None
    bcc: str | list[str] | None = None
    text: constr(min_length=1) | None = None
    html: constr(min_length=1) | None = None
    headers: dict[str, constr(min_length=1)] | None = Field(
        None, description='Custom headers to included with the emails'
    )
    attachments: list[dict[str, Any]] | None = Field(None, max_length=10)
    scheduledAt: AwareDatetime | None = None
    inReplyToId: str | None = None


class EmailsBatchPostRequest(RootModel[list[EmailsBatchPostRequestItem]]):
    root: list[EmailsBatchPostRequestItem] = Field(..., max_length=100)


class EmailsBatchPostResponse(BaseModel):
    pass


class EmailsEmailIdCancelPostResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsPostRequest(BaseModel):
    email: str
    firstName: str | None = None
    lastName: str | None = None
    properties: dict[str, str] | None = None
    subscribed: bool | None = None


class ContactBooksContactBookIdContactsPostResponse(BaseModel):
    contactId: str | None = None


class ContactBooksContactBookIdContactsGetParametersQuery(BaseModel):
    emails: str | None = None
    page: float | None = None
    limit: float | None = None
    ids: str | None = None


class ContactBooksContactBookIdContactsGetResponse(RootModel[list[dict[str, Any]]]):
    root: list[dict[str, Any]]


class ContactBooksContactBookIdContactsContactIdPatchRequest(BaseModel):
    firstName: str | None = None
    lastName: str | None = None
    properties: dict[str, str] | None = None
    subscribed: bool | None = None


class ContactBooksContactBookIdContactsContactIdPatchResponse(BaseModel):
    contactId: str | None = None


class ContactBooksContactBookIdContactsContactIdGetResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdPutRequest(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdPutResponse(BaseModel):
    pass


class ContactBooksContactBookIdContactsContactIdDeleteResponse(BaseModel):
    pass


class CampaignsPostRequest(BaseModel):
    name: constr(min_length=1)
    from_: constr(min_length=1) = Field(..., alias='from')
    subject: constr(min_length=1)
    previewText: str | None = None
    contactBookId: constr(min_length=1)
    content: constr(min_length=1) | None = None
    html: constr(min_length=1) | None = None
    replyTo: constr(min_length=1) | list[constr(min_length=1)] | None = None
    cc: constr(min_length=1) | list[constr(min_length=1)] | None = None
    bcc: constr(min_length=1) | list[constr(min_length=1)] | None = None
    sendNow: bool | None = None
    scheduledAt: str | None = Field(
        None,
        description="Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')",
    )
    batchSize: conint(ge=1, le=100000) | None = None


class CampaignsPostResponse(BaseModel):
    id: str
    name: str
    from_: str = Field(..., alias='from')
    subject: str
    previewText: str
    contactBookId: str
    html: str
    content: str
    status: str
    scheduledAt: AwareDatetime
    batchSize: int
    batchWindowMinutes: int
    total: int
    sent: int
    delivered: int
    opened: int
    clicked: int
    unsubscribed: int
    bounced: int
    hardBounced: int
    complained: int
    replyTo: list[str]
    cc: list[str]
    bcc: list[str]
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class CampaignsGetResponseItem(BaseModel):
    id: str
    name: str
    subject: str
    status: str | None = None
    created_at: str
    sent: float | None = 0
    delivered: float | None = 0
    opened: float | None = 0
    clicked: float | None = 0


class CampaignsGetResponse(RootModel[list[CampaignsGetResponseItem]]):
    root: list[CampaignsGetResponseItem]


class CampaignsCampaignIdGetResponse(BaseModel):
    id: str
    name: str
    from_: str = Field(..., alias='from')
    subject: str
    previewText: str
    contactBookId: str
    html: str
    content: str
    status: str
    scheduledAt: AwareDatetime
    batchSize: int
    batchWindowMinutes: int
    total: int
    sent: int
    delivered: int
    opened: int
    clicked: int
    unsubscribed: int
    bounced: int
    hardBounced: int
    complained: int
    replyTo: list[str]
    cc: list[str]
    bcc: list[str]
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class CampaignsCampaignIdSchedulePostRequest(BaseModel):
    scheduledAt: str | None = Field(
        None,
        description="Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')",
    )
    batchSize: conint(ge=1, le=100000) | None = None


class CampaignsCampaignIdSchedulePostResponse(BaseModel):
    pass


class CampaignsCampaignIdPausePostResponse(BaseModel):
    pass


class CampaignsCampaignIdResumePostResponse(BaseModel):
    pass


class ContactBooksPostRequest(BaseModel):
    name: constr(min_length=1)
    emoji: str | None = None
    properties: dict[str, str] | None = None


class ContactBooksPostResponse(BaseModel):
    id: str
    name: str
    emoji: str
    properties: Any | None = None
    teamId: str
    createdAt: str
    updatedAt: str


class ContactBooksGetResponse(RootModel[list[dict[str, Any]]]):
    root: list[dict[str, Any]]


class Details(BaseModel):
    totalContacts: float
    unsubscribedContacts: float
    campaigns: list[Any]


class ContactBooksIdGetResponse(BaseModel):
    id: str
    name: str
    emoji: str
    properties: Any | None = None
    teamId: str
    createdAt: str
    updatedAt: str
    details: Details


class ContactBooksIdPatchRequest(BaseModel):
    name: str | None = None
    emoji: str | None = None
    properties: dict[str, str] | None = None


class ContactBooksIdPatchResponse(BaseModel):
    id: str
    name: str


class ContactBooksIdDeleteResponse(BaseModel):
    success: bool


class TemplatesPostRequest(BaseModel):
    name: constr(min_length=1)
    subject: constr(min_length=1)
    html: str | None = None
    content: str | None = None


class TemplatesPostResponse(BaseModel):
    id: str


class TemplatesGetResponseItem(BaseModel):
    id: str
    name: str
    subject: str
    html: str | None = None
    content: str | None = None
    teamId: str
    createdAt: str
    updatedAt: str


class TemplatesGetResponse(RootModel[list[TemplatesGetResponseItem]]):
    root: list[TemplatesGetResponseItem]


class TemplatesIdGetResponse(BaseModel):
    id: str
    name: str
    subject: str
    html: str | None = None
    content: str | None = None
    teamId: str
    createdAt: str
    updatedAt: str


class TemplatesIdPatchRequest(BaseModel):
    name: str | None = None
    subject: str | None = None
    html: str | None = None
    content: str | None = None


class TemplatesIdPatchResponse(BaseModel):
    success: bool


class TemplatesIdDeleteResponse(BaseModel):
    success: bool


class Reason(Enum):
    HARD_BOUNCE = 'HARD_BOUNCE'
    COMPLAINT = 'COMPLAINT'
    MANUAL = 'MANUAL'
    UNSUBSCRIBE = 'UNSUBSCRIBE'


class SuppressionsGetParametersQuery(BaseModel):
    page: confloat(ge=1.0) | None = 1
    limit: confloat(ge=1.0, le=100.0) | None = 20
    search: str | None = None
    reason: Reason | None = None


class SuppressionsGetResponse(BaseModel):
    pass


class SuppressionsPostRequest(BaseModel):
    email: EmailStr
    reason: Reason
    source: str | None = None


class SuppressionsPostResponse(BaseModel):
    pass


class SuppressionsEmailEmailDeleteResponse(BaseModel):
    pass
